# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computePI <- function(D, homDim, res, sigma, minB, maxB, minP, maxP) {
    .Call(`_TDAvec_computePI`, D, homDim, res, sigma, minB, maxB, minP, maxP)
}

computePL <- function(D, homDim, k, scaleSeq) {
    .Call(`_TDAvec_computePL`, D, homDim, k, scaleSeq)
}

computePS <- function(D, homDim, p, scaleSeq) {
    .Call(`_TDAvec_computePS`, D, homDim, p, scaleSeq)
}

computeSWdist <- function(d1, d2, homDim, M = 10L) {
    .Call(`_TDAvec_computeSWdist`, d1, d2, homDim, M)
}

computeVAB <- function(D, homDim, scaleSeq) {
    .Call(`_TDAvec_computeVAB`, D, homDim, scaleSeq)
}

#' @export
computeVPB <- function(D, homDim, xSeq, ySeq, tau) {
    .Call(`_TDAvec_computeVPB`, D, homDim, xSeq, ySeq, tau)
}

rcpp_hello <- function() {
    .Call(`_TDAvec_rcpp_hello`)
}

